server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
    url: jdbc:postgresql://localhost:5432/odakiralamadb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
